<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0-windows10.0.19041.0</TargetFramework>
    <RootNamespace>NetCheck.Infrastructure</RootNamespace>
    <AssemblyName>NetCheck.Infrastructure</AssemblyName>
    <SupportedOSPlatformVersion>10.0.17763.0</SupportedOSPlatformVersion>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\NetCheck.Core\NetCheck.Core.csproj" />
  </ItemGroup>
</Project>
